# Generated by Django 5.1.7 on 2026-03-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HydrofoilAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='assets/hydrofoils/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(help_text='Mass of the vehicle in kg')),
                ('payload_weight', models.FloatField(help_text='Payload weight in kg')),
                ('center_of_gravity', models.JSONField(default=list, help_text='Center of gravity as an array [x, y, z]')),
                ('velocity', models.FloatField(help_text='Velocity in m/s')),
                ('angle_of_attack', models.FloatField(help_text='Angle of attack in degrees')),
                ('water_density', models.FloatField(default=1025.0, help_text='Water density in kg/m^3 (default 1025 for seawater)')),
                ('wave_height', models.FloatField(help_text='Wave height in meters')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MESHING', 'Meshing'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('current_logs', models.TextField(blank=True, help_text='Last 5 lines of solver output', null=True)),
                ('result_mesh_path', models.CharField(blank=True, help_text='Path to the reduced GLTF result', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='api.hydrofoilasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='api.project')),
            ],
        ),
    ]
