# Generated by GitHub Copilot on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='mesh_density',
            field=models.FloatField(
                default=1.0,
                help_text='Dimensionless base-mesh density multiplier (higher = finer base mesh)',
            ),
        ),
    ]
