# Generated by Django 5.1.7 on 2026-03-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_simulationrun_slice_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='submersion_depth',
            field=models.FloatField(default=0.5, help_text='Depth of the foil center below the water surface in meters'),
        ),
    ]
