# Generated by Django 5.1.7 on 2026-04-02 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_orientation_preview_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrofoilasset',
            name='file',
            field=models.FileField(upload_to='assets/hydrofoils/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'gltf', 'glb'])]),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='orientation_preview_url',
            field=models.CharField(blank=True, help_text='Relative media URL of the orientation preview GLB', max_length=500),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='api.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hydrofoilasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.folder'),
        ),
    ]
