# Generated by GitHub Copilot on 2026-05-02

from django.conf import settings
from django.db import migrations, models


def assign_legacy_team(apps, schema_editor):
    Team = apps.get_model('api', 'Team')
    Project = apps.get_model('api', 'Project')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    legacy_team, _ = Team.objects.get_or_create(name='Legacy Team')

    for user in User.objects.all():
        legacy_team.members.add(user)

    Project.objects.filter(team__isnull=True).update(team=legacy_team)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='projects', to='api.team'),
        ),
        migrations.RunPython(assign_legacy_team, migrations.RunPython.noop),
    ]