# Generated by GitHub Copilot on 2026-05-02

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_team_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TeamMembership',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('team', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='memberships', to='api.team')),
                        ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'api_team_members',
                        'ordering': ['team_id', 'user_id'],
                        'unique_together': {('team', 'user')},
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='teammembership',
            name='role',
            field=models.CharField(
                choices=[('viewer', 'Viewer'), ('engineer', 'Engineer'), ('team_admin', 'Team Admin')],
                default='team_admin',
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='created_at',
            field=models.DateTimeField(default=timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammembership',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now, auto_now=True),
            preserve_default=False,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='team',
                    name='members',
                    field=models.ManyToManyField(blank=True, related_name='teams', through='api.TeamMembership', to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],
        ),
    ]