# Generated by GitHub Copilot on 2026-05-03

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_team_membership_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('engineer', 'Engineer'), ('team_admin', 'Team Admin')], default='viewer', max_length=24)),
                ('token', models.CharField(default=api.models.generate_invite_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=24)),
                ('expires_at', models.DateTimeField(default=api.models.default_invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='accepted_team_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='sent_team_invites', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='invites', to='api.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]