# Generated by GitHub Copilot on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_team_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='delivery_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='send_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]