# Generated by GitHub Copilot on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_team_invite_delivery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrun",
            name="mesh_diagnostics",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]