# Generated by GitHub Copilot on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_simulationrun_mesh_diagnostics"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrun",
            name="celery_task_id",
            field=models.CharField(blank=True, default="", help_text="Celery task id for run lifecycle control", max_length=255),
        ),
        migrations.AlterField(
            model_name="simulationrun",
            name="status",
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MESHING', 'Meshing'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]